import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import StarBackground from "@/components/helpers/StarBackground";
import { Toaster } from "@/components/ui/toaster"
import { Analytics } from "@vercel/analytics/react"
const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Uthrathithan's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className="!scroll-smooth "
      lang="en"
      suppressHydrationWarning
    >
      <body className={` scrollbar-thin  scrollbar-rounded-sm  scrollbar-w-[2px] scrollbar-thumb-zinc-400 scrollbar-track-white dark:scrollbar-thumb-white dark:scrollbar-track-black ${font.className} `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="portfolio-theme"
        >
          <StarBackground />

          {children}
          <Analytics />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
