import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import StarBackground from "@/components/helpers/StarBackground";
import { Toaster } from "@/components/ui/toaster"

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "my portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className="!scroll-smooth "
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${font.className} `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="portfolio-theme"
        >
          <StarBackground />

          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
